IF Exists (SELECT * FROM TempDB..SysObjects WHERE id = OBJECT_ID('TempDB..#TmpPnt'))
  DROP TABLE #TmpPnt

     CREATE TABLE #TmpPnt (
	[ACCOUNT_ID] [int] NOT NULL ,
	[CONTRACT_ID] [int] NOT NULL ,
	[ACCOUNT_NAME] [varchar] (40) NULL ,
	[ADDRESS] [varchar] (40) NULL ,
	[AUDIT_TYPE_ID] [tinyint] NOT NULL ,
	[AUDIT_PARAM_ID] [tinyint] NOT NULL ,
	[AUDIT_METHOD_ID] [tinyint] NOT NULL ,
	[POWER_GROUP_ID] [tinyint] NOT NULL ,
	[BURNING_GROUP_ID] [tinyint] NULL ,
	[USE_HOUR] [varchar] (5) NULL ,
	[CALC_FACTOR] [decimal](9, 2) NOT NULL ,
	[LEGAL_DEVIATION] [tinyint] NOT NULL ,
	[ACCOUNT_OWNER_ID] [int] NOT NULL ,
	[TARIFF_ID] [int] NULL ,
	[STREET_ID] [smallint] NULL ,
	[HOUSE_ID] [varchar] (20) NULL ,
	[FLAT_ID] [varchar] (10) NULL ,
	[KNOT_MAIN] [varchar] (5) NULL ,
	[KNOT_OUT] [varchar] (12) NULL ,
	[SUBSTATION_TYPE_ID] [tinyint] NULL ,
	[SUBSTATION_ID] [varchar] (10) NULL ,
	[SECTION_ID] [tinyint] NULL ,
	[INDEX_F24_ID] [varchar] (5) NULL ,
	[CAPACITY] [decimal](9, 2) NULL ,
	[NODEID] [int] NULL ,
	[TRANC_POWER_ID] [int] NULL ,
	[TRANC_POWER_ACCOUNT_ID] [int] NULL ,
	[TRANC_POWER_METHOD_ID] [tinyint] NULL
 --,[AUDIT_METHOD_NAME] [varchar] (40) NOT NULL ,
--	[AUDIT_PARAM_NAME] [varchar] (40) NOT NULL ,
--	[AUDIT_TYPE_NAME] [varchar] (40) NOT NULL ,
--	[FACTORY_NUMBER] [varchar] (12) NOT NULL
) ON [PRIMARY]

insert into #TmpPnt
 (ACCOUNT_ID,
  CONTRACT_ID,
  ACCOUNT_NAME,
  ADDRESS,
  AUDIT_TYPE_ID,
  AUDIT_PARAM_ID,
  AUDIT_METHOD_ID,
  POWER_GROUP_ID,
  BURNING_GROUP_ID,
  USE_HOUR,
  CALC_FACTOR,
  LEGAL_DEVIATION,
  ACCOUNT_OWNER_ID,
  TARIFF_ID,
  STREET_ID,
  HOUSE_ID,
  FLAT_ID,
  KNOT_MAIN,
  KNOT_OUT,
  SUBSTATION_TYPE_ID,
  SUBSTATION_ID,
  SECTION_ID,
  INDEX_F24_ID,
  CAPACITY,
  NODEID,
  TRANC_POWER_ID,
  TRANC_POWER_ACCOUNT_ID,
  TRANC_POWER_METHOD_ID
--, AUDIT_METHOD_NAME,
--  AUDIT_PARAM_NAME,
--  AUDIT_TYPE_NAME,
--  FACTORY_NUMBER
)

Values (
133200103,
215411,
'Потери в ЛЭП',
NULL,
1,
3,
2,
0,
NULL,
'',
1.70,
99,
1332001,
54,
3208,
8,
NULL,
NULL,
'',
50,
'1879-ТП',
0,
16,
NULL,
1984,
NULL,
NULL,
NULL
--,'Постоянный расход',
--'Потери в ЛЭП',
--'Лимитированный расход',	
--''
)

/*
SELECT
A.ACCOUNT_ID,
A.CONTRACT_ID,
A.ACCOUNT_NAME,
A.ADDRESS,
A.AUDIT_TYPE_ID,
A.AUDIT_PARAM_ID,
A.AUDIT_METHOD_ID,
A.POWER_GROUP_ID,
A.BURNING_GROUP_ID,
A.USE_HOUR,
A.CALC_FACTOR,
A.LEGAL_DEVIATION,
A.ACCOUNT_OWNER_ID,
A.TARIFF_ID,
A.STREET_ID,
A.HOUSE_ID,
A.FLAT_ID,
A.KNOT_MAIN,
A.KNOT_OUT,
A.SUBSTATION_TYPE_ID,
A.SUBSTATION_ID,
A.SECTION_ID,
A.INDEX_F24_ID,
A.CAPACITY,
A.NODEID,
A.TRANC_POWER_ID,
A.TRANC_POWER_ACCOUNT_ID,
A.TRANC_POWER_METHOD_ID,
AM.AUDIT_METHOD_NAME,
AP.AUDIT_PARAM_NAME,
AT.AUDIT_TYPE_NAME,
FACTORY_NUMBER = ISNULL(CC.FACTORY_NUMBER,' - ???-')
 FROM
  ProAccounts A (NoLock),
  ProCntCounts CC (NoLock),
  ProAuditMethods AM (NoLock),
  ProAuditParams AP (NoLock),
  ProAuditTypes AT (NoLock)
 WHERE
  A.CONTRACT_ID=215411 AND
  CC.ACCOUNT_ID=*A.ACCOUNT_ID AND
  CC.DATE_ID='2004-07-31' AND
  AM.AUDIT_METHOD_ID=A.AUDIT_METHOD_ID AND
  AP.AUDIT_PARAM_ID=A.AUDIT_PARAM_ID AND
  AT.AUDIT_TYPE_ID=A.AUDIT_TYPE_ID
*/
  select * from #TmpPnt
--  DROP TABLE #TmpPnt
